#pragma once

enum SharedPaintCodeType {
	CODE_SYSTEM_JOIN_TO_SERVER,
	CODE_SYSTEM_JOIN_TO_SUPERPEER,
	CODE_SYSTEM_RES_JOIN,
	CODE_SYSTEM_LEFT,
	CODE_SYSTEM_TCPSYN,                                                                                                             
	CODE_SYSTEM_TCPACK,
	CODE_SYSTEM_CHANGE_SUPERPEER,
	CODE_SYSTEM_SYNC_REQUEST,
	CODE_SYSTEM_SYNC_START,
	CODE_SYSTEM_SYNC_COMPLETE,
	CODE_SYSTEM_VERSION_INFO,
	CODE_SYSTEM_CHANGE_NICKNAME,
	CODE_SYSTEM_CHAT_MESSAGE,
};
