#pragma once

enum SharedPaintCodeType {
	CODE_SYSTEM_JOIN,
	CODE_SYSTEM_LEFT,
	CODE_PAINT_SET_BG_IMAGE,
	CODE_PAINT_SET_BG_COLOR,
	CODE_PAINT_SET_BG_GRID_LINE,
	CODE_PAINT_CLEAR_BG,
	CODE_PAINT_CLEAR_SCREEN,
	CODE_PAINT_CREATE_ITEM,
	CODE_TASK_EXECUTE,
	CODE_WINDOW_RESIZE_MAIN_WND,
	CODE_BROAD_SERVER_INFO,
	CODE_BROAD_TEXT_MESSAGE,
	CODE_MAX,
};
