#pragma once

enum SharedPaintCodeType {
	CODE_PAINT_ADD_ITEM,
	CODE_PAINT_UPDATE_ITEM,
	CODE_PAINT_SET_BG_IMAGE,
	CODE_PAINT_SET_BG_COLOR,
	CODE_PAINT_SET_BG_GRID_LINE,
	CODE_PAINT_CLEAR_BG,
	CODE_PAINT_MOVE_ITEM,
	CODE_PAINT_REMOVE_ITEM,
	CODE_PAINT_CLEAR_SCREEN,
	CODE_WINDOW_RESIZE_MAIN_WND,
	CODE_SYSTEM_JOIN,
	CODE_SYSTEM_LEFT,
	CODE_BROAD_SERVER_INFO,
	CODE_MAX,
};
