#pragma once 

#define VERSION_TEXT	"0.8"
#define AUTHOR_TEXT		"gunoodaddy"
#define PROGRAME_TEXT	"Shared Painter"

#define NET_MAGIC_CODE	0xBE

#define DEFAULT_TEXT_ITEM_POS_REGION_W	9999
#define DEFAULT_TEXT_ITEM_POS_REGION_H	300

#define DEFAULT_PIXMAP_ITEM_SIZE_W	250

#define DEFAULT_TRAY_MESSAGE_DURATION_MSEC	5000
